Fileserver Doku hizugefügt
quotengrote/dp_schulserver pull request #12
Opened 2020-08-25 12:07 UTC by DanielMueller1309

2020-08-25 16:10 UTC, quotengrote commented on Gesamtdoku/v0.5.md
> +Für die Bereitstellung des Speichers, der DX80 muss zuerst auf dem mpath-device ein Dateisystem erstellt werden.
Hier fehlt wie überhaupt multipath eingerichtet wird

2020-08-25 16:10 UTC, quotengrote commented on Gesamtdoku/v0.5.md
> +Liegt nur ein Blockdevice ohne Physisches Volumen, Volumengruppe und oder Logisches Volumen vor müssen diese mit `pvcreate`, `vgcreate` und `lvcreate` erstellt werden.
Was hat das mit "nur einem blockdevice" zu tun?

2020-08-25 16:11 UTC, quotengrote commented on Gesamtdoku/v0.5.md
> +`/dev/mapper/mpathb_vg-data   /mnt/dx80_r5  ext4   defaults   0   2`
damit wird beim start automatisch eingehangen, ABER nicht sofort gemountet, dafür benötigt man `mount -a` <-- mountet alle in der fstab eingetragen dateisysteme

2020-08-25 16:11 UTC, quotengrote commented on Gesamtdoku/v0.5.md
> +`chmod 777 && chown root:users`
bei den befehel fehlt jeweils auf welchen ordner sie ausgeführt werden

2020-08-25 16:12 UTC, quotengrote requested changes
Wie in den Kommentaren beschrieben...

2020-08-26 11:37 UTC, DanielMueller1309 commented on Gesamtdoku/v0.5.md
> +Liegt nur ein Blockdevice ohne Physisches Volumen, Volumengruppe und oder Logisches Volumen vor müssen diese mit `pvcreate`, `vgcreate` und `lvcreate` erstellt werden.
"Wenn auf einem Blockdevice weder Physische Volumen, Volumengruppen... angelegt sind.... anlegen" würde das besser klingen? Wollte mir selbst damit nur eine Gedächtnisstütze anlegen.

2020-08-26 11:38 UTC, DanielMueller1309 commented on Gesamtdoku/v0.5.md
> +Für die Bereitstellung des Speichers, der DX80 muss zuerst auf dem mpath-device ein Dateisystem erstellt werden.
wird ergänzt

2020-08-26 14:11 UTC, DanielMueller1309 commented on Gesamtdoku/v0.5.md
> +`/dev/mapper/mpathb_vg-data   /mnt/dx80_r5  ext4   defaults   0   2`
wird ergänzt

2020-08-26 16:02 UTC, DanielMueller1309 commented on Gesamtdoku/v0.5.md
> +`chmod 777 && chown root:users`
Doch das ganze soll im erstellten Freigabeordner ausgeführt werden

2020-08-28 10:44 UTC, quotengrote commented on Gesamtdoku/v0.5.md
> +Liegt nur ein Blockdevice ohne Physisches Volumen, Volumengruppe und oder Logisches Volumen vor müssen diese mit `pvcreate`, `vgcreate` und `lvcreate` erstellt werden.
Da kann man auch einfach LVM schreiben, wie das gemacht wird ist dann ja klar.

2020-08-28 10:45 UTC, quotengrote commented on Gesamtdoku/v0.5.md
> +`chmod 777 && chown root:users`
Das funktioniert so nicht, der Pfad muss dem Befehl als Argument mitgegeben werden.

2020-08-28 10:46 UTC, quotengrote commented on Gesamtdoku/v0.5.md
> +  - [multipath.conf](./Anleitungen/Multipath/multipath.conf)
Typo * Stelle

2020-08-28 10:47 UTC, quotengrote requested changes

2020-08-28 10:47 UTC, quotengrote commented on Gesamtdoku/v0.5.md
> +
Hier könnte noch mit rein das PVE seine LV selber erstellt pro VM

2020-09-07 12:26 UTC, merged