Dokumentation für Schüler bearbeitet
quotengrote/dp_schulserver pull request #34
Opened 2020-11-01 17:43 UTC by MaxGoe

Doku Schüler wurde fortgesetzt und vervollständigt
Bilder zur simpleren Darstellung wurden eingefügt
Siehe LoginPVE.png (Bild Login Screen) PoolView.png (Ansicht Poolview
bzw. wo man in diese wechseln kann, und Suchleiste.png (Beispiel wie IP
in Browser eingefügt werden kann).

2020-11-01 17:46 UTC, quotengrote requested changes
Das ganze bitte noch als nummerierte Liste, ließt sich dann besser.

2020-11-01 17:46 UTC, quotengrote commented on Gesamtdoku/Doku_Schueler.md
> +Der Nutzername sowie das Passwort weißt euch der Lehrer zu. Hier sollte darauf geachtet werden, dass unter Realm: ProxMox VE Authentication Server ausgewählt wird.
Typo: weißt

2020-11-01 17:46 UTC, quotengrote commented on Gesamtdoku/Doku_Schueler.md
> +Seid ihr nun in der PVE Oberfläche und habt die Warnmeldung eueres Browsers übersprungen sehr ihr nun folgende Übersicht.
Typo: sehr

2020-11-01 17:46 UTC, quotengrote commented on Gesamtdoku/Doku_Schueler.md
> +Dann anschließend die euch vom Lehrer vergebene IP oben in die Suchleiste eingeben.
Wieso vergibt der Lehrer hier was?

2020-11-01 17:48 UTC, MaxGoe commented on Gesamtdoku/Doku_Schueler.md
> +Dann anschließend die euch vom Lehrer vergebene IP oben in die Suchleiste eingeben.
Vielleicht unglücklich formuliert hierbei sollte lediglich darauf abgezielt werden das die Schüler die IP für das WebGui vom Lehrer mitgeteilt werden

2020-11-01 18:54 UTC, quotengrote commented on Gesamtdoku/Doku_Schueler.md
> +Dann anschließend die euch vom Lehrer vergebene IP oben in die Suchleiste eingeben.
mit gefällts nicht, was sagt der Rest dazu?

2020-11-02 07:48 UTC, MaxGoe commented
> Das ganze bitte noch als nummerierte Liste, liest sich dann besser.

Was genau meinst du damit?

2020-11-02 09:14 UTC, quotengrote commented
1. text
2. text
<n>. text

2020-11-02 09:15 UTC, quotengrote commented
@Kati-20DP Worauf beziehen sich die Anmerkungen?

2020-11-02 09:16 UTC, quotengrote commented on Gesamtdoku/Doku_Schueler.md
> +Der Nutzername sowie das Passwort weißt euch der Lehrer zu. Hier sollte darauf geachtet werden, dass unter Realm: ProxMox VE Authentication Server ausgewählt wird.
> > Das ganze bitte noch als nummerierte Liste, liest sich dann besser.
> 
> Was genau meinst du damit?

```
1. text
2. text
<n>. text
```

2020-11-02 09:24 UTC, Kati-20DP commented
@quotengrote: Ich hatte die Anmerkungen eigentlich an den entsprechenden Zeilen gemacht. Keine Ahnung, warum er das so komisch anzeigt?

2020-11-02 09:25 UTC, quotengrote commented
Wer weiß, @MaxGoe wann kommen die Changes? ;-D

2020-11-02 09:46 UTC, quotengrote requested changes

2020-11-02 09:46 UTC, quotengrote commented on Gesamtdoku/Doku_Schueler.md
> +**2. ProxMox Übersicht**
Jain, ich meinte eigentlich die Anleitung darunter und nicht die Überschriften.

2020-11-02 09:53 UTC, MaxGoe commented on Gesamtdoku/Doku_Schueler.md
> +**2. ProxMox Übersicht**
:D Alles klar mach ich noch schnell.

2020-11-02 10:26 UTC, quotengrote commented on Gesamtdoku/Doku_Schueler.md
> +**2. ProxMox Übersicht**
Wir reden hier aneinander vorbei, ich  andere das mal.

2020-11-02 10:39 UTC, quotengrote commented
Falls du an dem Branch noch weiter arbeiten willst, denk dran vorher deinen lokalen Branch zu aktualisieren.

2020-11-02 12:35 UTC, merged